[package]
name = "sci-units-proc-macro"
version = "0.6.0"
edition = "2024"
license = "MIT"
description = "Procedural macros for use with sci-units."
repository = "https://github.com/tyler-gilbert/sci-units"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["visit-mut"] }
quote = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[features]
std = []
defmt = []
